highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://myjekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Yu Tian's Resume
name: Yu Tian
email: yu.tian8328@gmail.com
email_full: mailto:yu.tian8328@gmail.com
website: yutian8328/github.io/
website_full: https://yutian8328.github.io/vitea
github: trending
tel: +41 8084700
tel_full: tel:+418084700
google_maps: 'lace/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Kirjaty 
  postcode: 00170
  city: Edinburgh
  country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
